config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  get 'webrtc' => 'webrtc#index'
  get 'createacl' => 'users#provision_credential_list'
  get 'createipcl' => 'users#provision_ip_list'
  get 'deleteipacl' => 'users#delete_ip_list'
  get 'deleteacl' => 'users#delete_credential_list'
  get 'number' => 'users#add_number'
  get 'domain' => 'users#add_domain'

  post 'adduser' => 'users#add_user'
  post 'addip' => 'users#add_ip'
  post 'incoming' => 'twilio#return_twiml'


  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users
end

app/controllers/webrtc_controller.rb
# Prepares the main WebRTC view to be rendered
class WebrtcController < ApplicationController
  before_filter :authenticate_user!

  def index
    @agent = current_user
    @agent_name = current_user.name
    @token = capability_token
    @client = create_rest_client

    unless @agent.phone_number.nil?
      @number = @agent.phone_number
    end

    unless @agent.sip_domain.nil?
      @domain = @agent.sip_domain
    end

    if @agent.ip_acl.nil?
      @ip_acl_partial = 'create_ipacl'
    else
      @ip_acl_partial = 'ipacl'
      @ip_acl = @client.account.sip.ip_access_control_lists.get(@agent.ip_acl)
    end

    if @agent.auth_acl.nil?
      @acl_partial = 'create_acl'
    else
      @acl_partial = 'acl'
      @auth_acl = @client.account.sip.credential_lists.get(@agent.auth_acl)
    end
  end

  def capability_token
    capability = Twilio::Util::Capability.new(
      Rails.application.secrets.twilio_account_sid,
      Rails.application.secrets.twilio_auth_token)
    capability.allow_client_incoming current_user.id
    capability.generate
  end

  def create_rest_client
    Twilio::REST::Client.new(
      Rails.application.secrets.twilio_account_sid,
      Rails.application.secrets.twilio_auth_token)
  end
end

app/helpers/webrtchelper.rb
module WebrtcHelper
end

app/views/webrtc/_acl.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal2">
  Configure credential list
</button>

<!-- Modal -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Credential List</h4>
      </div>
      <div class="modal-body">
        <form action="adduser" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <div class="form-group col-md-6">
            <label>User Name</label>
            <% @auth_acl.credentials.list.each do |credentials| %>
              <tr>
                <%= render partial: "well", object: credentials.username%>
              </tr>
            <% end %>
            <input type="name" class="form-control" name="username" placeholder="JoeTelecom">
          </div>
          <div class="form-group col-md-6">
            <label>Password</label>
              <% @auth_acl.credentials.list.each do |credentials| %>
                <tr>
                  <%= render partial: "well", object: "•••••••••••"%>
                </tr>
              <% end %>
            <input type="ip" class="form-control" name="password" placeholder="alphanumeric">
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
          <a href=<%= deleteacl_path %> role="button" class="btn btn-danger">Delete</a>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/webrtc/_create_acl.html.erb
 <button type="button" class="btn btn-success" onclick="window.location.href='/createacl'">Create credential list</button>

app/views/webrtc/_create_ipacl.html.erb
<button type="button" class="btn btn-success" onclick="window.location.href='/createipcl'">Create IP whitelist</button>

app/views/webrtc/_ipacl.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
          Configure IP whitelist
        </button>

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">IP Access Control List</h4>
              </div>
              <div class="modal-body">
                <form action="addip" method="post">
                  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                  <div class="form-group col-md-6">
                    <label>Friendly Name</label>
                    <% @ip_acl.ip_addresses.list.each do |ipAddress| %>
                      <tr>
                        <%= render partial: "well", object: ipAddress.friendly_name%>
                      </tr>
                    <% end %>
                    <input type="name" class="form-control" name="friendlyname" placeholder="Friendly Name">
                  </div>
                  <div class="form-group col-md-6">
                    <label>IP Address</label>
                      <% @ip_acl.ip_addresses.list.each do |ipAddress| %>
                        <tr>
                          <%= render partial: "well", object: ipAddress.ip_address%>
                        </tr>
                      <% end %>
                    <input type="ip" class="form-control" name="ip" placeholder="192.168.2.1">
                  </div>
                  <button type="submit" class="btn btn-primary">Submit</button>
                  <a href=<%= deleteipacl_path %> role="button" class="btn btn-danger">Delete</a>
                </form>
              </div>
            </div>
          </div>
        </div>

app/views/webrtc/_provision_domain.html.erb
 <button type="button" class="btn btn-success" onclick="window.location.href='/domain'">Provision SIP Domain</button>

app/views/webrtc/_provision_number.html.erb
 <button type="button" class="btn btn-success" onclick="window.location.href='/number'">Provision Number</button>

app/views/webrtc/_softphone.html.erb
<hr/>
<div class="well well-lg">
  <table class="table">
  <tr>
    <td>To:</td>
    <td id="to"></td>
  </tr>
    <tr>
    <td>From:</td>
    <td id="from"></td>
  </tr>
</table>
  <div class="btn-group btn-group-justified" role="group">
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-success" onclick="accept();">
        Accept
      </button>
    </div>
    <div class="btn-group" role="group">
    <button id="hangup-btn" type="button" class="btn btn-danger" onclick="hangup();">
      Hangup
    </button>
  </div>
  <div class="btn-group" role="group">
    <button id="mute-btn" type="button" class="btn" onclick="mute();">
      Mute
    </button>
  </div>
  </div>
  <div class="alert alert-info text-center" id="log" >Connecting to Twilio...</div>
</div>

app/views/webrtc/_well.html.erb
<div class="well well-sm"><%= well %></div>

app/views/webrtc/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <hr/>
      <h3>Call this number</h3>
      <div class="well well-sm">
        <% if @number.nil? %>
          <%= render "provision_number" %>
        <% else %>
          <%= @number%>
        <% end %>
      </div>
      <h3>Send calls to this SIP address</h3>
      <div class="well well-sm">
      <% if @domain.nil? %>
        <%= render "provision_domain" %>
      <% else %>
        <%= @domain%>
      <% end %></div>
      <% if @domain %>
        <%= render @ip_acl_partial %>
        <%= render @acl_partial %>
      <% end %>
    </div>
    <div class="col-md-4">
      <%= render 'softphone' %>
    </div>
    <div class="col-md-4">
    </div>
  </div>
</div>

<script type="text/javascript">

var ready;
ready = function()  {

  Twilio.Device.setup("<%= @token %>", {debug: true});

  /* Let us know when the client is ready. */
  Twilio.Device.ready(function (device) {
    $("#log").text("Client is ready ");
    $("#log").toggleClass("alert-info alert-success");
  });
 
  /* Report any errors on the screen */
  Twilio.Device.error(function (error) {
    $("#log").text("Error: " + error.message);
    $("#log").toggleClass("alert-info alert-success");
  });
 
  Twilio.Device.connect(function (conn) {
    $("#log").text("Call connected");
  });
  
  Twilio.Device.disconnect(function (conn) {
    $("#log").text("Call ended");
    $("#to").empty();
    $("#from").empty();
  });

  Twilio.Device.incoming(function (conn) {
    $("#log").text("Incoming call");
    $("#to").text("<%= @agent_name%>");
    $("#from").text(conn.parameters.From);

    $("#hangup-btn").text("Reject");
    $("#hangup-btn").attr("onclick","reject()");
  });

};

$(document).ready(ready);
$(document).on('page:load', ready);


  function hangup() {
    Twilio.Device.disconnectAll();
    $("#to").empty();
    $("#from").empty();
  }

  function accept() {
    Twilio.Device.activeConnection().accept();
    $("#log").text("Connection active");
    $("#hangup-btn").text("Hangup");
    $("#hangup-btn").attr("onclick","hangup()");
  }

    function reject() {
    Twilio.Device.activeConnection().reject();
    $("#log").text("Connection rejected");
    $("#hangup-btn").text("Hangup");
    $("#hangup-btn").attr("onclick","hangup()");
    $("#to").empty();
    $("#from").empty();
  }

  function mute() {
    if (Twilio.Device.activeConnection().isMuted() == false) {
      Twilio.Device.activeConnection().mute(true);
      $( "#mute-btn" ).addClass( "btn-danger" );
      }
    else { if (Twilio.Device.activeConnection().isMuted() == true)
      Twilio.Device.activeConnection().mute(false);
      $( "#mute-btn" ).removeClass( "btn-danger" );
      }
  }

</script>