config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  get 'webrtc' => 'webrtc#index'
  get 'createacl' => 'users#provision_credential_list'
  get 'createipcl' => 'users#provision_ip_list'
  get 'deleteipacl' => 'users#delete_ip_list'
  get 'deleteacl' => 'users#delete_credential_list'
  get 'number' => 'users#add_number'
  get 'domain' => 'users#add_domain'

  post 'adduser' => 'users#add_user'
  post 'addip' => 'users#add_ip'
  post 'incoming' => 'twilio#return_twiml'


  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-center footer-text">Made with ❤︎ by Twilio London. Source can be found <a href="https://github.com/akjordan/sip-to-webrtc">here</a>.</p>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'WebRTC', webrtc_path%></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? && current_user.id == 122 %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SIP to WebRTC" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "SIP to WebRTC" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag '//static.twilio.com/libs/twiliojs/1.2/twilio.min.js' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>